language: node_js
node_js:
 — "12.18.3"
branches:
 only:
 — main
before_script:
 — npm install -g ionic
 — npm ci 
script:
 — ionic build --prod -- --base-href ./
deploy:
 provider: pages
 skip-cleanup: true
 github-token: 51f6d97259decf4f3c8388c671a28a00b8c4d8b1 
 keep-history: true
 on:
   branch: main
 local_dir: build